language: python
python:
  - '2.6'
  - '2.7'
  - '3.2'
  - '3.3'
  - 'pypy'
install:
  - 'pip install -r reqs-dev.txt --use-mirrors --quiet'
script: py.test --cov=argh
notifications:
  email:
    - neithere+travis@gmail.com
