language: python
python:
  - '2.6'
  - '2.7'
  - '3.2'
  - '3.3'
  #- 'pypy'    # omitting due to obscure early segfault on PyPy 2.2.0
install:
  - 'pip install -r reqs-dev.txt'
script: py.test --cov=argh
notifications:
  email:
    - neithere+travis@gmail.com
